version: 2.1

jobs:
  test:
    docker:
      - image: 'cimg/node:14.14.0'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: node --version

workflows:
  alpha:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.+(-alpha).*/

  beta:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.+(-beta).*/
  
  prod:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
